version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: dev_clinic_user
      POSTGRES_PASSWORD: dev_clinic_password
      POSTGRES_DB: dev_clinic_db
    ports:
      - '5441:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: nextjs_app
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://dev_clinic_user:dev_clinic_password@postgres:5432/dev_clinic_db
    depends_on:
      - postgres

volumes:
  postgres_data:

