/*
  Warnings:

  - You are about to drop the column `antecedentes` on the `Historia_Clinica` table. All the data in the column will be lost.
  - You are about to drop the column `medicamentos` on the `Historia_Clinica` table. All the data in the column will be lost.
  - You are about to drop the column `tratamientos` on the `Historia_Clinica` table. All the data in the column will be lost.

*/
-- AlterTable
ALTER TABLE "Historia_Clinica" DROP COLUMN "antecedentes",
DROP COLUMN "medicamentos",
DROP COLUMN "tratamientos",
ADD COLUMN     "alta_paciente" TEXT,
ADD COLUMN     "antecedente_alcohol" BOOLEAN,
ADD COLUMN     "antecedente_anemia" BOOLEAN,
ADD COLUMN     "antecedente_ar" BOOLEAN,
ADD COLUMN     "antecedente_asma" BOOLEAN,
ADD COLUMN     "antecedente_dengue" BOOLEAN,
ADD COLUMN     "antecedente_dm" BOOLEAN,
ADD COLUMN     "antecedente_familiar_anemia" BOOLEAN,
ADD COLUMN     "antecedente_familiar_asma" BOOLEAN,
ADD COLUMN     "antecedente_familiar_dm" BOOLEAN,
ADD COLUMN     "antecedente_familiar_hta" BOOLEAN,
ADD COLUMN     "antecedente_familiar_iam" BOOLEAN,
ADD COLUMN     "antecedente_familiar_tbc" BOOLEAN,
ADD COLUMN     "antecedente_farmacologicos" TEXT,
ADD COLUMN     "antecedente_fiebre_amarilla" BOOLEAN,
ADD COLUMN     "antecedente_hta" BOOLEAN,
ADD COLUMN     "antecedente_iam" BOOLEAN,
ADD COLUMN     "antecedente_its" BOOLEAN,
ADD COLUMN     "antecedente_les" BOOLEAN,
ADD COLUMN     "antecedente_lidocaina" BOOLEAN,
ADD COLUMN     "antecedente_mercurialismo" BOOLEAN,
ADD COLUMN     "antecedente_otros_epidemiologicos" TEXT,
ADD COLUMN     "antecedente_otros_familiares" TEXT,
ADD COLUMN     "antecedente_otros_generales" TEXT,
ADD COLUMN     "antecedente_otros_inmunologicos" TEXT,
ADD COLUMN     "antecedente_otros_ocupacionales" TEXT,
ADD COLUMN     "antecedente_otros_patologicos" TEXT,
ADD COLUMN     "antecedente_ram" BOOLEAN,
ADD COLUMN     "antecedente_stress" BOOLEAN,
ADD COLUMN     "antecedente_tabaco" BOOLEAN,
ADD COLUMN     "antecedente_tbc" BOOLEAN,
ADD COLUMN     "antecedente_trauma_acustico" BOOLEAN,
ADD COLUMN     "antecedente_vih" BOOLEAN,
ADD COLUMN     "antecedentes_familiares" TEXT,
ADD COLUMN     "antecedentes_personales" TEXT,
ADD COLUMN     "apetito" TEXT,
ADD COLUMN     "cel_apoderado" TEXT,
ADD COLUMN     "cie10_definitivo" TEXT,
ADD COLUMN     "cie10_presuntivo" TEXT,
ADD COLUMN     "control_evolucion" TEXT,
ADD COLUMN     "correo_apoderado" TEXT,
ADD COLUMN     "deposicion" TEXT,
ADD COLUMN     "dni_apoderado" TEXT,
ADD COLUMN     "enfermedad_actual" TEXT,
ADD COLUMN     "especificacion_antecedentes" TEXT,
ADD COLUMN     "examen_extraoral" TEXT,
ADD COLUMN     "examen_intraoral" TEXT,
ADD COLUMN     "examen_ocl" TEXT,
ADD COLUMN     "f_resp" TEXT,
ADD COLUMN     "fc" TEXT,
ADD COLUMN     "fecha" TEXT,
ADD COLUMN     "funciones_biologicas" TEXT,
ADD COLUMN     "hc" TEXT,
ADD COLUMN     "hora" TEXT,
ADD COLUMN     "miccion" TEXT,
ADD COLUMN     "motivo_consulta" TEXT,
ADD COLUMN     "nombre_apoderado" TEXT,
ADD COLUMN     "plan_tratamiento" TEXT,
ADD COLUMN     "profesional_nombre" TEXT,
ADD COLUMN     "pronostico" TEXT,
ADD COLUMN     "pulso" TEXT,
ADD COLUMN     "recomendaciones" TEXT,
ADD COLUMN     "relato_cronologico" TEXT,
ADD COLUMN     "sed" TEXT,
ADD COLUMN     "signos_pa" TEXT,
ADD COLUMN     "signos_sintomas" TEXT,
ADD COLUMN     "temp" TEXT,
ADD COLUMN     "tiempo_enfermedad" TEXT;

-- AlterTable
ALTER TABLE "Paciente" ADD COLUMN     "direccion" TEXT,
ADD COLUMN     "edad" TEXT,
ADD COLUMN     "emergencia" TEXT,
ADD COLUMN     "estado_civil" TEXT,
ADD COLUMN     "grado_instruccion" TEXT,
ADD COLUMN     "lugar_fecha_nacimiento" TEXT,
ADD COLUMN     "ocupacion" TEXT,
ADD COLUMN     "procedencia" TEXT,
ADD COLUMN     "religion" TEXT,
ADD COLUMN     "sexo" "Sexo",
ADD COLUMN     "telefono" TEXT,
ADD COLUMN     "viajes" TEXT;
